/**
 * Scientific formula registry — 14 supported versioned calculations (Phase 6C.6).
 */

import type { ScientificFormulaDefinition } from '../models/calculation/ScientificCalculation';
import { bilingual } from './seedHelpers';

function input(
  key: string,
  en: string,
  ar: string,
  unit: string,
  required = true,
  min?: number,
  max?: number
) {
  return { key, label: bilingual(en, ar), unit, required, min, max };
}

function formula(partial: ScientificFormulaDefinition): ScientificFormulaDefinition {
  return partial;
}

export const SCIENTIFIC_FORMULA_REGISTRY: ScientificFormulaDefinition[] = [
  formula({
    formula_id: 'formula_bmi',
    key: 'bmi',
    version: '1.0.0',
    version_number: 1,
    name: bilingual('Body Mass Index', 'مؤشر كتلة الجسم'),
    description: bilingual('Mass relative to height squared', 'الكتلة بالنسبة لمربع الطول'),
    evidence_tier: 'screening',
    required_inputs: [
      input('weight_kg', 'Body weight', 'وزن الجسم', 'kg', true, 0.1, 300),
      input('height_cm', 'Height', 'الطول', 'cm', true, 50, 250),
    ],
    optional_inputs: [],
    output_metric: 'bmi',
    output_unit: 'kg/m²',
    supported_assessment_definition_keys: ['bmi'],
    validation_rules: ['no_negative_weight', 'no_negative_height'],
    citation_ids: ['cite_who_bmi'],
    expression_key: 'bmi_mass_height',
    active: true,
  }),
  formula({
    formula_id: 'formula_body_fat',
    key: 'body_fat',
    version: '1.0.0',
    version_number: 1,
    name: bilingual('Body Fat %', 'نسبة دهون الجسم'),
    description: bilingual('Circumference-based body fat estimate', 'تقدير دهون الجسم من المحيط'),
    evidence_tier: 'screening',
    required_inputs: [
      input('waist_cm', 'Waist circumference', 'محيط الخصر', 'cm', true, 40, 200),
      input('neck_cm', 'Neck circumference', 'محيط الرقبة', 'cm', true, 20, 60),
      input('height_cm', 'Height', 'الطول', 'cm', true, 50, 250),
    ],
    optional_inputs: [input('hip_cm', 'Hip circumference', 'محيط الورك', 'cm', false, 40, 200)],
    output_metric: 'body_fat_percent',
    output_unit: '%',
    supported_assessment_definition_keys: ['body_fat', 'skinfold'],
    validation_rules: ['invalid_body_fat_range', 'no_negative_height'],
    citation_ids: ['cite_navy_method'],
    expression_key: 'body_fat_navy',
    active: true,
  }),
  formula({
    formula_id: 'formula_lean_body_mass',
    key: 'lean_body_mass',
    version: '1.0.0',
    version_number: 1,
    name: bilingual('Lean Body Mass', 'كتلة الجسم النحيل'),
    description: bilingual('Fat-free mass from weight and body fat', 'كتلة خالية من الدهون'),
    evidence_tier: 'field',
    required_inputs: [
      input('weight_kg', 'Body weight', 'وزن الجسم', 'kg', true, 0.1, 300),
      input('body_fat_percent', 'Body fat %', 'نسبة الدهون', '%', true, 0, 60),
    ],
    optional_inputs: [],
    output_metric: 'lean_body_mass_kg',
    output_unit: 'kg',
    supported_assessment_definition_keys: ['body_fat', 'bia_analysis'],
    validation_rules: ['invalid_body_fat_range', 'no_negative_weight'],
    citation_ids: ['cite_lean_mass'],
    expression_key: 'lean_body_mass',
    active: true,
  }),
  formula({
    formula_id: 'formula_muscle_mass',
    key: 'muscle_mass',
    version: '1.0.0',
    version_number: 1,
    name: bilingual('Muscle Mass', 'كتلة العضلات'),
    description: bilingual('Estimated skeletal muscle mass', 'تقدير كتلة العضلات الهيكلية'),
    evidence_tier: 'field',
    required_inputs: [input('lean_body_mass_kg', 'Lean body mass', 'كتلة الجسم النحيل', 'kg', true, 1, 200)],
    optional_inputs: [],
    output_metric: 'muscle_mass_kg',
    output_unit: 'kg',
    supported_assessment_definition_keys: ['skeletal_muscle_mass', 'bia_analysis'],
    validation_rules: ['no_negative_weight'],
    citation_ids: ['cite_muscle_mass_estimate'],
    expression_key: 'muscle_mass',
    active: true,
  }),
  formula({
    formula_id: 'formula_body_water',
    key: 'body_water_percent',
    version: '1.0.0',
    version_number: 1,
    name: bilingual('Body Water %', 'نسبة ماء الجسم'),
    description: bilingual('Total body water estimate from lean mass', 'تقدير ماء الجسم الكلي'),
    evidence_tier: 'field',
    required_inputs: [
      input('weight_kg', 'Body weight', 'وزن الجسم', 'kg', true, 0.1, 300),
      input('lean_body_mass_kg', 'Lean body mass', 'كتلة الجسم النحيل', 'kg', true, 1, 200),
    ],
    optional_inputs: [],
    output_metric: 'body_water_percent',
    output_unit: '%',
    supported_assessment_definition_keys: ['bia_analysis'],
    validation_rules: ['no_negative_weight'],
    citation_ids: ['cite_body_water'],
    expression_key: 'body_water_percent',
    active: true,
  }),
  formula({
    formula_id: 'formula_vo2max',
    key: 'vo2max',
    version: '1.0.0',
    version_number: 1,
    name: bilingual('VO₂ Max (Field)', 'VO₂ Max ميداني'),
    description: bilingual('Cooper-style field aerobic estimate', 'تقدير هوائي ميداني'),
    evidence_tier: 'field',
    required_inputs: [
      input('distance_m', 'Distance', 'المسافة', 'm', true, 100, 5000),
      input('age_years', 'Age', 'العمر', 'years', true, 10, 80),
    ],
    optional_inputs: [],
    output_metric: 'vo2_max',
    output_unit: 'ml/kg/min',
    supported_assessment_definition_keys: ['cooper', 'vo2max_est'],
    validation_rules: ['no_negative_distance'],
    citation_ids: ['cite_cooper_1968'],
    expression_key: 'vo2max_cooper_field',
    active: true,
  }),
  formula({
    formula_id: 'formula_hr_zones',
    key: 'hr_zones',
    version: '1.0.0',
    version_number: 1,
    name: bilingual('HR Zones', 'مناطق ضربات القلب'),
    description: bilingual('Age-predicted maximum heart rate', 'الحد الأقصى لضربات القلب حسب العمر'),
    evidence_tier: 'screening',
    required_inputs: [input('age_years', 'Age', 'العمر', 'years', true, 10, 80)],
    optional_inputs: [input('resting_hr', 'Resting HR', 'معدل الراحة', 'bpm', false, 30, 120)],
    output_metric: 'max_heart_rate',
    output_unit: 'bpm',
    supported_assessment_definition_keys: ['resting_heart_rate', 'heart_rate_recovery'],
    validation_rules: ['invalid_hr'],
    citation_ids: ['cite_hr_zones'],
    expression_key: 'hr_zones',
    active: true,
  }),
  formula({
    formula_id: 'formula_training_load',
    key: 'training_load',
    version: '1.0.0',
    version_number: 1,
    name: bilingual('Training Load', 'حمل التدريب'),
    description: bilingual('Session RPE load', 'حمل الجلسة RPE'),
    evidence_tier: 'professional',
    required_inputs: [
      input('duration_min', 'Duration', 'المدة', 'min', true, 1, 600),
      input('rpe', 'RPE', 'RPE', 'score', true, 0, 10),
    ],
    optional_inputs: [],
    output_metric: 'session_load',
    output_unit: 'AU',
    supported_assessment_definition_keys: ['training_monotony', 'playerload'],
    validation_rules: ['no_negative_duration'],
    citation_ids: ['cite_foster_2001'],
    expression_key: 'session_rpe_load',
    active: true,
  }),
  formula({
    formula_id: 'formula_acwr',
    key: 'acwr',
    version: '1.0.0',
    version_number: 1,
    name: bilingual('ACWR', 'ACWR'),
    description: bilingual('Acute:chronic workload ratio', 'نسبة الحمل الحاد إلى المزمن'),
    evidence_tier: 'professional',
    required_inputs: [
      input('acute_load', 'Acute load', 'الحمل الحاد', 'AU', true, 0, 10000),
      input('chronic_load', 'Chronic load', 'الحمل المزمن', 'AU', true, 0.1, 10000),
    ],
    optional_inputs: [],
    output_metric: 'acwr',
    output_unit: 'ratio',
    supported_assessment_definition_keys: ['playerload', 'training_strain'],
    validation_rules: ['no_division_by_zero'],
    citation_ids: ['cite_gabbett_2016'],
    expression_key: 'acwr_ratio',
    active: true,
  }),
  formula({
    formula_id: 'formula_recovery',
    key: 'recovery_score',
    version: '1.0.0',
    version_number: 1,
    name: bilingual('Recovery Score', 'درجة التعافي'),
    description: bilingual('Wellness-based recovery composite', 'مؤشر تعافي من العافية'),
    evidence_tier: 'field',
    required_inputs: [
      input('sleep_quality', 'Sleep quality', 'جودة النوم', 'score', true, 1, 10),
      input('soreness', 'Muscle soreness', 'ألم العضلات', 'score', true, 1, 10),
      input('fatigue', 'Fatigue', 'الإجهاد', 'score', true, 1, 10),
    ],
    optional_inputs: [],
    output_metric: 'recovery_score',
    output_unit: 'score',
    supported_assessment_definition_keys: ['hooper_index', 'tqr', 'restq_sport'],
    validation_rules: [],
    citation_ids: ['cite_recovery_composite'],
    expression_key: 'recovery_composite',
    active: true,
  }),
  formula({
    formula_id: 'formula_readiness',
    key: 'readiness_score',
    version: '1.0.0',
    version_number: 1,
    name: bilingual('Readiness Score', 'درجة الجاهزية'),
    description: bilingual('Multi-factor readiness composite', 'مؤشر جاهزية متعدد العوامل'),
    evidence_tier: 'professional',
    required_inputs: [
      input('wellness_score', 'Wellness score', 'درجة العافية', 'score', true, 0, 100),
      input('cmj_delta', 'CMJ delta %', 'تغير CMJ %', '%', true, -50, 50),
      input('hrv_score', 'HRV score', 'درجة HRV', 'score', true, 0, 100),
    ],
    optional_inputs: [],
    output_metric: 'readiness_score',
    output_unit: '%',
    supported_assessment_definition_keys: ['cmj_fatigue_monitoring', 'hrv_rmssd'],
    validation_rules: [],
    citation_ids: ['cite_readiness_practice'],
    expression_key: 'readiness_composite',
    active: true,
  }),
  formula({
    formula_id: 'formula_relative_strength',
    key: 'relative_strength',
    version: '1.0.0',
    version_number: 1,
    name: bilingual('Relative Strength', 'القوة النسبية'),
    description: bilingual('External load relative to body weight', 'الحمل الخارجي بالنسبة لوزن الجسم'),
    evidence_tier: 'professional',
    required_inputs: [
      input('load_kg', 'External load', 'الحمل الخارجي', 'kg', true, 0.1, 500),
      input('body_weight_kg', 'Body weight', 'وزن الجسم', 'kg', true, 0.1, 300),
    ],
    optional_inputs: [],
    output_metric: 'relative_1rm',
    output_unit: '× BW',
    supported_assessment_definition_keys: ['squat_1rm', 'bench_1rm', 'deadlift_1rm'],
    validation_rules: ['no_negative_weight', 'no_division_by_zero'],
    citation_ids: ['cite_relative_strength'],
    expression_key: 'relative_strength',
    active: true,
  }),
  formula({
    formula_id: 'formula_sprint_momentum',
    key: 'sprint_momentum',
    version: '1.0.0',
    version_number: 1,
    name: bilingual('Sprint Momentum', 'زخم Sprint'),
    description: bilingual('Mass × velocity sprint momentum', 'الكتلة × السرعة'),
    evidence_tier: 'research',
    required_inputs: [
      input('body_mass_kg', 'Body mass', 'كتلة الجسم', 'kg', true, 30, 150),
      input('velocity_m_s', 'Velocity', 'السرعة', 'm/s', true, 0.1, 15),
    ],
    optional_inputs: [],
    output_metric: 'sprint_momentum',
    output_unit: 'kg·m/s',
    supported_assessment_definition_keys: ['sprint_momentum'],
    validation_rules: ['no_negative_weight'],
    citation_ids: ['cite_sprint_momentum'],
    expression_key: 'sprint_momentum',
    active: true,
  }),
  formula({
    formula_id: 'formula_running_speed',
    key: 'running_speed',
    version: '1.0.0',
    version_number: 1,
    name: bilingual('Running Speed', 'سرعة الجري'),
    description: bilingual('Speed from distance and time', 'السرعة من المسافة والزمن'),
    evidence_tier: 'field',
    required_inputs: [
      input('distance_m', 'Distance', 'المسافة', 'm', true, 1, 5000),
      input('time_s', 'Time', 'الزمن', 's', true, 0.1, 3600),
    ],
    optional_inputs: [],
    output_metric: 'speed_m_s',
    output_unit: 'm/s',
    supported_assessment_definition_keys: ['sprint5', 'sprint10', 'sprint20', 'sprint30', 'flying_sprint'],
    validation_rules: ['no_division_by_zero', 'no_negative_distance'],
    citation_ids: ['cite_running_speed'],
    expression_key: 'running_speed',
    active: true,
  }),
];

export const SUPPORTED_FORMULA_COUNT = SCIENTIFIC_FORMULA_REGISTRY.length;

const FORMULA_KEY_ALIASES: Record<string, string> = {
  readiness: 'readiness_score',
};

export function getFormulaDefinitionByKey(key: string): ScientificFormulaDefinition | null {
  const resolvedKey = FORMULA_KEY_ALIASES[key] ?? key;
  return SCIENTIFIC_FORMULA_REGISTRY.find((f) => f.key === resolvedKey && f.active) ?? null;
}

export function listActiveFormulaDefinitions(): ScientificFormulaDefinition[] {
  return SCIENTIFIC_FORMULA_REGISTRY.filter((f) => f.active);
}
