import type { CatalogEquipmentType } from '../models/catalog/EquipmentCatalog';
import { bilingual, seedDocumentMeta } from './seedHelpers';

export const SEED_EQUIPMENT_TYPES: CatalogEquipmentType[] = [
  {
    ...seedDocumentMeta('eq_type_force_plate'),
    key: 'force_plate',
    name: bilingual('Force Plate', 'منصة القوة'),
    description: bilingual('Ground reaction force measurement', 'قياس قوة ارتداد الأرض'),
    default_calibration_interval_days: 365,
    default_sampling_frequency_hz: 1000,
    supported_assessment_definition_ids: ['cmj', 'imtp', 'rsi_mod'],
    evidence_tier_ceiling: 'research',
    active: true,
  },
  {
    ...seedDocumentMeta('eq_type_gps'),
    key: 'gps',
    name: bilingual('GPS System', 'نظام GPS'),
    description: bilingual('External load and movement tracking', 'تتبع الحركة والحمل الخارجي'),
    default_calibration_interval_days: 180,
    supported_assessment_definition_ids: ['gps_session_load'],
    evidence_tier_ceiling: 'professional',
    active: true,
  },
  {
    ...seedDocumentMeta('eq_type_hrm'),
    key: 'heart_rate_monitor',
    name: bilingual('Heart Rate Monitor', 'مراقب نبض القلب'),
    description: bilingual('HR and HRV capture', 'تسجيل نبض القلب وتقلب النبض'),
    default_calibration_interval_days: 365,
    supported_assessment_definition_ids: ['hr_zones', 'lactate_step_test'],
    evidence_tier_ceiling: 'professional',
    active: true,
  },
  {
    ...seedDocumentMeta('eq_type_lactate'),
    key: 'lactate_analyzer',
    name: bilingual('Lactate Analyzer', 'محلل Lactate'),
    description: bilingual('Blood lactate measurement', 'قياس Lactate الدم'),
    default_calibration_interval_days: 90,
    supported_assessment_definition_ids: ['lactate_threshold'],
    evidence_tier_ceiling: 'research',
    active: true,
  },
  {
    ...seedDocumentMeta('eq_type_dexa'),
    key: 'dexa',
    name: bilingual('DEXA', 'DEXA'),
    description: bilingual('Dual-energy X-ray absorptiometry', 'امتصاص الأشعة السينية ثنائي الطاقة'),
    default_calibration_interval_days: 365,
    supported_assessment_definition_ids: ['body_composition_dexa'],
    evidence_tier_ceiling: 'clinical',
    active: true,
  },
  {
    ...seedDocumentMeta('eq_type_bia'),
    key: 'bia',
    name: bilingual('BIA Device', 'جهاز BIA'),
    description: bilingual('Bioelectrical impedance analysis', 'تحليل المعاوقة الحيوية'),
    default_calibration_interval_days: 180,
    supported_assessment_definition_ids: ['body_composition_bia'],
    evidence_tier_ceiling: 'professional',
    active: true,
  },
  {
    ...seedDocumentMeta('eq_type_spirometry'),
    key: 'spirometry',
    name: bilingual('Spirometry', 'قياس التنفس'),
    description: bilingual('Pulmonary function testing', 'اختبار وظائف الرئة'),
    default_calibration_interval_days: 365,
    supported_assessment_definition_ids: ['spirometry_fvc'],
    evidence_tier_ceiling: 'clinical',
    active: true,
  },
  {
    ...seedDocumentMeta('eq_type_timing_gates'),
    key: 'timing_gates',
    name: bilingual('Timing Gates', 'بوابات التوقيت'),
    description: bilingual('Sprint split timing', 'توقيت splits السprint'),
    default_calibration_interval_days: 180,
    supported_assessment_definition_ids: ['sprint_30m', 'sprint_10m', 'flying_sprint'],
    evidence_tier_ceiling: 'field',
    active: true,
  },
  {
    ...seedDocumentMeta('eq_type_jump_mat'),
    key: 'jump_mat',
    name: bilingual('Jump Mat', 'بساط القفز'),
    description: bilingual('Contact time and jump height', 'زمن التماس وارتفاع القفز'),
    default_calibration_interval_days: 365,
    default_sampling_frequency_hz: 250,
    supported_assessment_definition_ids: ['cmj'],
    evidence_tier_ceiling: 'field',
    active: true,
  },
  {
    ...seedDocumentMeta('eq_type_dynamometer'),
    key: 'dynamometer',
    name: bilingual('Dynamometer', 'Dynamometer'),
    description: bilingual('Isometric and isokinetic force', 'قياس القوة الثابتة والحركية'),
    default_calibration_interval_days: 365,
    supported_assessment_definition_ids: ['grip_strength', 'imtp', 'isokinetic_hq'],
    evidence_tier_ceiling: 'research',
    active: true,
  },
  {
    ...seedDocumentMeta('eq_type_laboratory'),
    key: 'laboratory_equipment',
    name: bilingual('Laboratory Equipment', 'معدات مخبرية'),
    description: bilingual('CPET carts and lab instruments', 'أجهزة CPET والمختبر'),
    default_calibration_interval_days: 365,
    supported_assessment_definition_ids: ['cpet_vo2max', 'blood_panel'],
    evidence_tier_ceiling: 'clinical',
    active: true,
  },
];
