import type { CatalogFormula, CatalogFormulaVersion } from '../models/catalog/FormulaRegistry';
import { bilingual, seedDocumentMeta, seedVersionMeta } from './seedHelpers';

export const SEED_FORMULA_VERSIONS: CatalogFormulaVersion[] = [
  {
    ...seedDocumentMeta('formula_bmi_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_bmi',
    expression_key: 'bmi_mass_height',
    input_keys: ['weight_kg', 'height_cm'],
    output_key: 'bmi',
    output_unit: 'kg/m²',
    evidence_tier: 'screening',
    citation_ids: ['cite_who_bmi'],
    notes: bilingual('BMI = weight / height²', 'مؤشر كتلة الجسم = الوزن / الطول²'),
  },
  {
    ...seedDocumentMeta('formula_body_fat_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_body_fat',
    expression_key: 'body_fat_navy',
    input_keys: ['waist_cm', 'neck_cm', 'height_cm'],
    output_key: 'body_fat_percent',
    output_unit: '%',
    evidence_tier: 'screening',
    citation_ids: ['cite_navy_method'],
    notes: bilingual('Circumference-based body fat estimate', 'تقدير دهون الجسم من المحيط'),
  },
  {
    ...seedDocumentMeta('formula_lean_body_mass_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_lean_body_mass',
    expression_key: 'lean_body_mass',
    input_keys: ['weight_kg', 'body_fat_percent'],
    output_key: 'lean_body_mass_kg',
    output_unit: 'kg',
    evidence_tier: 'field',
    citation_ids: ['cite_lean_mass'],
    notes: bilingual('Fat-free mass from weight and body fat', 'كتلة خالية من الدهون'),
  },
  {
    ...seedDocumentMeta('formula_muscle_mass_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_muscle_mass',
    expression_key: 'muscle_mass',
    input_keys: ['lean_body_mass_kg'],
    output_key: 'muscle_mass_kg',
    output_unit: 'kg',
    evidence_tier: 'field',
    citation_ids: ['cite_muscle_mass_estimate'],
    notes: bilingual('Estimated skeletal muscle mass', 'تقدير كتلة العضلات الهيكلية'),
  },
  {
    ...seedDocumentMeta('formula_body_water_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_body_water',
    expression_key: 'body_water_percent',
    input_keys: ['weight_kg', 'lean_body_mass_kg'],
    output_key: 'body_water_percent',
    output_unit: '%',
    evidence_tier: 'field',
    citation_ids: ['cite_body_water'],
    notes: bilingual('Total body water estimate from lean mass', 'تقدير ماء الجسم الكلي'),
  },
  {
    ...seedDocumentMeta('formula_vo2max_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_vo2max',
    expression_key: 'vo2max_cooper_field',
    input_keys: ['distance_m', 'age_years'],
    output_key: 'vo2_max',
    output_unit: 'ml/kg/min',
    evidence_tier: 'field',
    citation_ids: ['cite_cooper_1968'],
    notes: bilingual('Field estimate from Cooper-style inputs', 'تقدير ميداني من مدخلات Cooper'),
  },
  {
    ...seedDocumentMeta('formula_hr_zones_v2'),
    ...seedVersionMeta('1.1.0'),
    formula_id: 'formula_hr_zones',
    expression_key: 'hr_zones',
    input_keys: ['age_years', 'resting_hr', 'hr_zone_method'],
    output_key: 'max_heart_rate',
    output_unit: 'bpm',
    evidence_tier: 'screening',
    citation_ids: ['cite_hr_zones'],
    notes: bilingual(
      'Five HR zones via %HRmax or Karvonen',
      'خمس مناطق لضربات القلب عبر %HRmax أو Karvonen'
    ),
  },
  {
    ...seedDocumentMeta('formula_training_load_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_training_load',
    expression_key: 'session_rpe_load',
    input_keys: ['duration_min', 'rpe'],
    output_key: 'session_load',
    output_unit: 'AU',
    evidence_tier: 'professional',
    citation_ids: ['cite_foster_2001'],
    notes: bilingual('Session load = duration × RPE', 'حمل الجلسة = المدة × RPE'),
  },
  {
    ...seedDocumentMeta('formula_acwr_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_acwr',
    expression_key: 'acwr_ratio',
    input_keys: ['acute_load', 'chronic_load'],
    output_key: 'acwr',
    output_unit: 'ratio',
    evidence_tier: 'professional',
    citation_ids: ['cite_gabbett_2016'],
    notes: bilingual('Acute:chronic workload ratio', 'نسبة الحمل الحاد إلى المزمن'),
  },
  {
    ...seedDocumentMeta('formula_recovery_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_recovery',
    expression_key: 'recovery_composite',
    input_keys: ['sleep_quality', 'soreness', 'fatigue'],
    output_key: 'recovery_score',
    output_unit: 'score',
    evidence_tier: 'field',
    citation_ids: ['cite_recovery_composite'],
    notes: bilingual('Wellness-based recovery composite', 'مؤشر تعافي من العافية'),
  },
  {
    ...seedDocumentMeta('formula_readiness_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_readiness',
    expression_key: 'readiness_composite',
    input_keys: ['wellness_score', 'cmj_delta', 'hrv_score'],
    output_key: 'readiness_score',
    output_unit: '%',
    evidence_tier: 'professional',
    citation_ids: ['cite_readiness_practice'],
    notes: bilingual('Composite readiness index', 'مؤشر جاهزية مركّب'),
  },
  {
    ...seedDocumentMeta('formula_relative_strength_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_relative_strength',
    expression_key: 'relative_strength',
    input_keys: ['load_kg', 'body_weight_kg'],
    output_key: 'relative_1rm',
    output_unit: '× BW',
    evidence_tier: 'professional',
    citation_ids: ['cite_relative_strength'],
    notes: bilingual('External load relative to body weight', 'الحمل الخارجي بالنسبة لوزن الجسم'),
  },
  {
    ...seedDocumentMeta('formula_sprint_momentum_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_sprint_momentum',
    expression_key: 'sprint_momentum',
    input_keys: ['body_mass_kg', 'velocity_m_s'],
    output_key: 'sprint_momentum',
    output_unit: 'kg·m/s',
    evidence_tier: 'research',
    citation_ids: ['cite_sprint_momentum'],
    notes: bilingual('Mass × velocity sprint momentum', 'الكتلة × السرعة'),
  },
  {
    ...seedDocumentMeta('formula_running_speed_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_running_speed',
    expression_key: 'running_speed',
    input_keys: ['distance_m', 'time_s'],
    output_key: 'speed_m_s',
    output_unit: 'm/s',
    evidence_tier: 'field',
    citation_ids: ['cite_running_speed'],
    notes: bilingual('Speed from distance and time', 'السرعة من المسافة والزمن'),
  },
];

export const SEED_FORMULAS: CatalogFormula[] = [
  {
    ...seedDocumentMeta('formula_bmi'),
    ...seedVersionMeta('1.0.0'),
    key: 'bmi',
    name: bilingual('Body Mass Index', 'مؤشر كتلة الجسم'),
    description: bilingual('Mass relative to height squared', 'الكتلة بالنسبة لمربع الطول'),
    current_version_id: 'formula_bmi_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_body_fat'),
    ...seedVersionMeta('1.0.0'),
    key: 'body_fat',
    name: bilingual('Body Fat Estimate', 'تقدير دهون الجسم'),
    description: bilingual('Field body fat from circumferences', 'دهون الجسم من المحيطات'),
    current_version_id: 'formula_body_fat_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_lean_body_mass'),
    ...seedVersionMeta('1.0.0'),
    key: 'lean_body_mass',
    name: bilingual('Lean Body Mass', 'كتلة الجسم النحيل'),
    description: bilingual('Fat-free mass from weight and body fat', 'كتلة خالية من الدهون'),
    current_version_id: 'formula_lean_body_mass_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_muscle_mass'),
    ...seedVersionMeta('1.0.0'),
    key: 'muscle_mass',
    name: bilingual('Muscle Mass', 'كتلة العضلات'),
    description: bilingual('Estimated skeletal muscle mass', 'تقدير كتلة العضلات الهيكلية'),
    current_version_id: 'formula_muscle_mass_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_body_water'),
    ...seedVersionMeta('1.0.0'),
    key: 'body_water_percent',
    name: bilingual('Body Water %', 'نسبة ماء الجسم'),
    description: bilingual('Total body water estimate from lean mass', 'تقدير ماء الجسم الكلي'),
    current_version_id: 'formula_body_water_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_vo2max'),
    ...seedVersionMeta('1.0.0'),
    key: 'vo2max',
    name: bilingual('VO₂max Estimate', 'تقدير VO₂max'),
    description: bilingual('Field aerobic capacity estimate', 'تقدير اللياقة الهوائية الميدانية'),
    current_version_id: 'formula_vo2max_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_hr_zones'),
    ...seedVersionMeta('1.1.0'),
    key: 'hr_zones',
    name: bilingual('HR Zones', 'مناطق ضربات القلب'),
    description: bilingual(
      'Five heart rate zones via %HRmax or Karvonen',
      'خمس مناطق لضربات القلب عبر %HRmax أو Karvonen'
    ),
    current_version_id: 'formula_hr_zones_v2',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_training_load'),
    ...seedVersionMeta('1.0.0'),
    key: 'training_load',
    name: bilingual('Training Load', 'حمل التدريب'),
    description: bilingual('Internal session load (sRPE)', 'حمل الجلسة الداخلي (sRPE)'),
    current_version_id: 'formula_training_load_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_acwr'),
    ...seedVersionMeta('1.0.0'),
    key: 'acwr',
    name: bilingual('ACWR', 'ACWR'),
    description: bilingual('Acute:chronic workload ratio', 'نسبة الحمل الحاد إلى المزمن'),
    current_version_id: 'formula_acwr_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_recovery'),
    ...seedVersionMeta('1.0.0'),
    key: 'recovery_score',
    name: bilingual('Recovery Score', 'درجة التعافي'),
    description: bilingual('Wellness-based recovery composite', 'مؤشر تعافي من العافية'),
    current_version_id: 'formula_recovery_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_readiness'),
    ...seedVersionMeta('1.0.0'),
    key: 'readiness_score',
    name: bilingual('Readiness Score', 'درجة الجاهزية'),
    description: bilingual('Multi-factor readiness composite', 'مؤشر جاهزية متعدد العوامل'),
    current_version_id: 'formula_readiness_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_relative_strength'),
    ...seedVersionMeta('1.0.0'),
    key: 'relative_strength',
    name: bilingual('Relative Strength', 'القوة النسبية'),
    description: bilingual('External load relative to body weight', 'الحمل الخارجي بالنسبة لوزن الجسم'),
    current_version_id: 'formula_relative_strength_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_sprint_momentum'),
    ...seedVersionMeta('1.0.0'),
    key: 'sprint_momentum',
    name: bilingual('Sprint Momentum', 'زخم Sprint'),
    description: bilingual('Mass × velocity sprint momentum', 'الكتلة × السرعة'),
    current_version_id: 'formula_sprint_momentum_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_running_speed'),
    ...seedVersionMeta('1.0.0'),
    key: 'running_speed',
    name: bilingual('Running Speed', 'سرعة الجري'),
    description: bilingual('Speed from distance and time', 'السرعة من المسافة والزمن'),
    current_version_id: 'formula_running_speed_v1',
    active: true,
  },
];

export const SEED_FORMULA_COUNT = SEED_FORMULAS.length;
