import type { CatalogFormula, CatalogFormulaVersion } from '../models/catalog/FormulaRegistry';
import { bilingual, seedDocumentMeta, seedVersionMeta } from './seedHelpers';

export const SEED_FORMULA_VERSIONS: CatalogFormulaVersion[] = [
  {
    ...seedDocumentMeta('formula_bmi_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_bmi',
    expression_key: 'bmi_mass_height',
    input_keys: ['weight_kg', 'height_cm'],
    output_key: 'bmi',
    output_unit: 'kg/m²',
    evidence_tier: 'screening',
    citation_ids: ['cite_who_bmi'],
    notes: bilingual('BMI = weight / height²', 'مؤشر كتلة الجسم = الوزن / الطول²'),
  },
  {
    ...seedDocumentMeta('formula_vo2max_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_vo2max',
    expression_key: 'vo2max_cooper_field',
    input_keys: ['distance_m', 'age_years'],
    output_key: 'vo2_max',
    output_unit: 'ml/kg/min',
    evidence_tier: 'field',
    citation_ids: ['cite_cooper_1968'],
    notes: bilingual('Field estimate from Cooper-style inputs', 'تقدير ميداني من مدخلات Cooper'),
  },
  {
    ...seedDocumentMeta('formula_training_load_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_training_load',
    expression_key: 'session_rpe_load',
    input_keys: ['duration_min', 'rpe'],
    output_key: 'session_load',
    output_unit: 'AU',
    evidence_tier: 'professional',
    citation_ids: ['cite_foster_2001'],
    notes: bilingual('Session load = duration × RPE', 'حمل الجلسة = المدة × RPE'),
  },
  {
    ...seedDocumentMeta('formula_acwr_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_acwr',
    expression_key: 'acwr_ratio',
    input_keys: ['acute_load', 'chronic_load'],
    output_key: 'acwr',
    output_unit: 'ratio',
    evidence_tier: 'professional',
    citation_ids: ['cite_gabbett_2016'],
    notes: bilingual('Acute:chronic workload ratio', 'نسبة الحمل الحاد إلى المزمن'),
  },
  {
    ...seedDocumentMeta('formula_readiness_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_readiness',
    expression_key: 'readiness_composite',
    input_keys: ['wellness_score', 'cmj_delta', 'hrv_score'],
    output_key: 'readiness_score',
    output_unit: '%',
    evidence_tier: 'professional',
    citation_ids: ['cite_readiness_practice'],
    notes: bilingual('Composite readiness index', 'مؤشر جاهزية مركّب'),
  },
  {
    ...seedDocumentMeta('formula_body_fat_v1'),
    ...seedVersionMeta('1.0.0'),
    formula_id: 'formula_body_fat',
    expression_key: 'body_fat_navy',
    input_keys: ['waist_cm', 'neck_cm', 'height_cm'],
    output_key: 'body_fat_percent',
    output_unit: '%',
    evidence_tier: 'screening',
    citation_ids: ['cite_navy_method'],
    notes: bilingual('Circumference-based body fat estimate', 'تقدير دهون الجسم من المحيط'),
  },
];

export const SEED_FORMULAS: CatalogFormula[] = [
  {
    ...seedDocumentMeta('formula_bmi'),
    ...seedVersionMeta('1.0.0'),
    key: 'bmi',
    name: bilingual('Body Mass Index', 'مؤشر كتلة الجسم'),
    description: bilingual('Mass relative to height squared', 'الكتلة بالنسبة لمربع الطول'),
    current_version_id: 'formula_bmi_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_vo2max'),
    ...seedVersionMeta('1.0.0'),
    key: 'vo2max',
    name: bilingual('VO₂max Estimate', 'تقدير VO₂max'),
    description: bilingual('Field aerobic capacity estimate', 'تقدير اللياقة الهوائية الميدانية'),
    current_version_id: 'formula_vo2max_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_training_load'),
    ...seedVersionMeta('1.0.0'),
    key: 'training_load',
    name: bilingual('Training Load', 'حمل التدريب'),
    description: bilingual('Internal session load (sRPE)', 'حمل الجلسة الداخلي (sRPE)'),
    current_version_id: 'formula_training_load_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_acwr'),
    ...seedVersionMeta('1.0.0'),
    key: 'acwr',
    name: bilingual('ACWR', 'ACWR'),
    description: bilingual('Acute:chronic workload ratio', 'نسبة الحمل الحاد إلى المزمن'),
    current_version_id: 'formula_acwr_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_readiness'),
    ...seedVersionMeta('1.0.0'),
    key: 'readiness',
    name: bilingual('Readiness Score', 'درجة الجاهزية'),
    description: bilingual('Multi-factor readiness composite', 'مؤشر جاهزية متعدد العوامل'),
    current_version_id: 'formula_readiness_v1',
    active: true,
  },
  {
    ...seedDocumentMeta('formula_body_fat'),
    ...seedVersionMeta('1.0.0'),
    key: 'body_fat',
    name: bilingual('Body Fat Estimate', 'تقدير دهون الجسم'),
    description: bilingual('Field body fat from circumferences', 'دهون الجسم من المحيطات'),
    current_version_id: 'formula_body_fat_v1',
    active: true,
  },
];
