import type { CatalogSport } from '../models/catalog/Sport';
import { bilingual, seedDocumentMeta } from './seedHelpers';

export const SEED_SPORTS: CatalogSport[] = [
  {
    ...seedDocumentMeta('sport_football'),
    key: 'football',
    name: bilingual('Football (Soccer)', 'كرة القدم'),
    category: 'team',
    positions: ['goalkeeper', 'defender', 'midfielder', 'forward'],
    typical_assessment_definition_ids: ['yo_yo_ir1', 'cmj', 'sprint_30m'],
    active: true,
  },
  {
    ...seedDocumentMeta('sport_basketball'),
    key: 'basketball',
    name: bilingual('Basketball', 'كرة السلة'),
    category: 'team',
    positions: ['guard', 'forward', 'center'],
    typical_assessment_definition_ids: ['cmj', 'pro_agility', 'sprint_20m'],
    active: true,
  },
  {
    ...seedDocumentMeta('sport_athletics'),
    key: 'athletics',
    name: bilingual('Athletics', 'ألعاب القوى'),
    category: 'individual',
    positions: ['sprinter', 'middle_distance', 'jumps', 'throws'],
    typical_assessment_definition_ids: ['sprint_100m', 'cmj', 'vo2max_cooper'],
    active: true,
  },
  {
    ...seedDocumentMeta('sport_swimming'),
    key: 'swimming',
    name: bilingual('Swimming', 'السباحة'),
    category: 'individual',
    positions: ['freestyle', 'backstroke', 'breaststroke', 'butterfly'],
    typical_assessment_definition_ids: ['vo2max_cooper', 'body_composition_dexa'],
    active: true,
  },
  {
    ...seedDocumentMeta('sport_rugby'),
    key: 'rugby',
    name: bilingual('Rugby', 'الرجبي'),
    category: 'team',
    positions: ['forward', 'back'],
    typical_assessment_definition_ids: ['yo_yo_ir1', 'cmj', 'sprint_40m'],
    active: true,
  },
  {
    ...seedDocumentMeta('sport_volleyball'),
    key: 'volleyball',
    name: bilingual('Volleyball', 'الكرة الطائرة'),
    category: 'team',
    positions: ['setter', 'outside_hitter', 'middle_blocker', 'libero'],
    typical_assessment_definition_ids: ['cmj', 'vertical_jump', 'pro_agility'],
    active: true,
  },
  {
    ...seedDocumentMeta('sport_tennis'),
    key: 'tennis',
    name: bilingual('Tennis', 'التنس'),
    category: 'individual',
    positions: ['singles', 'doubles'],
    typical_assessment_definition_ids: ['pro_agility', 'cmj', 'yo_yo_ir1'],
    active: true,
  },
  {
    ...seedDocumentMeta('sport_combat'),
    key: 'combat',
    name: bilingual('Combat Sports', 'رياضات قتالية'),
    category: 'individual',
    positions: ['lightweight', 'middleweight', 'heavyweight'],
    typical_assessment_definition_ids: ['cmj', 'grip_strength', 'body_composition'],
    active: true,
  },
];
