export * from './types';
export { MEAL_SLOTS, SUPPLEMENT_CATALOG, NUTRITION_GOALS } from './registry/nutritionCatalog';
export { buildNutritionSnapshot, computeMacroTotals, computeBmi, computeComplianceBreakdown } from './engine/nutritionEngine';
export { analyzeBodyComposition, computeWaistHipRatio } from './engine/bodyCompositionEngine';
export { buildAthleteNutritionSnapshot, buildNutritionEngineInput, formatNutritionForAI, resolveNutritionGoal } from './utils/nutritionHelpers';
export { buildNutritionSignals } from './utils/nutritionSignals';
export { useNutritionSnapshot } from './hooks/useNutritionSnapshot';
export { NutritionCenterPanel } from './components/NutritionCenterPanel';
export { WorkspaceNutritionSection } from './components/WorkspaceNutritionSection';
export { NutritionLogForm } from './components/NutritionLogForm';
export { BodyCompositionForm, BodyCompositionHistoryPanel } from './components/BodyCompositionPanel';
