/** Maps library test keys to primary analytics signal keys used in module scoring. */
export const TEST_SIGNAL_ALIASES: Record<string, string> = {
  sprint5: 'sprint30',
  sprint10: 'sprint30',
  sprint20: 'sprint30',
  sprint40: 'sprint30',
  flying_sprint: 'sprint30',
  rsa: 'sprint30',
  sprint_momentum: 'sprint30',
  acceleration_test: 'sprint30',
  max_velocity_test: 'sprint30',
  bench_1rm: 'squat_1rm',
  deadlift_1rm: 'squat_1rm',
  grip_strength: 'squat_1rm',
  imtp: 'squat_1rm',
  nordic_hamstring: 'squat_1rm',
  pullup: 'squat_1rm',
  pushup: 'squat_1rm',
  med_ball_throw: 'cmj',
  leg_press: 'squat_1rm',
  yoyo_ir2: 'yoyo',
  bruce: 'cooper',
  astrand: 'cooper',
  balke: 'cooper',
  vo2max_est: 'cooper',
  mas: 'cooper',
  lactate_threshold: 'cooper',
  t_test: 'illinois',
  test_505: 'illinois',
  pro_agility: 'illinois',
  reactive_agility: 'illinois',
  zigzag: 'illinois',
  squat_jump: 'cmj',
  drop_jump: 'cmj',
  broad_jump: 'cmj',
  vertical_jump: 'cmj',
  reactive_strength_index: 'cmj_rsi',
  triple_hop: 'cmj',
  shoulder_mobility: 'sit_reach',
  thomas_test: 'sit_reach',
  hip_rotation: 'sit_reach',
  ankle_dorsiflexion: 'sit_reach',
  stork_balance: 'y_balance',
  sebt: 'y_balance',
  single_leg_balance: 'y_balance',
  bmi: 'body_fat',
  skeletal_muscle_mass: 'body_fat',
  waist_hip_ratio: 'body_fat',
  skinfold: 'body_fat',
  audio_reaction: 'visual_reaction',
  choice_reaction: 'visual_reaction',
  decision_reaction: 'visual_reaction',
  reactive_jump: 'cmj_rsi',
  landing_mechanics: 'cmj_rsi',
  force_symmetry: 'cmj_rsi',
  deep_squat: 'fms',
  hurdle_step: 'fms',
  inline_lunge: 'fms',
  aslr: 'fms',
  shoulder_mobility_screen: 'fms',
};

export function resolveSignalKey(testTypeKey: string): string {
  return TEST_SIGNAL_ALIASES[testTypeKey] ?? testTypeKey;
}
