import type { AnalyticsModuleId } from '@/src/analytics/types';
import { copyBundle, defineTests, refs } from '../factory';
import type { TestDefinition } from '../../types';

const MOD: AnalyticsModuleId[] = ['endurance', 'physical_fitness', 'fatigue'];
const MOD_LOAD: AnalyticsModuleId[] = ['endurance', 'physical_fitness', 'training_load'];

function distance(
  key: string,
  nameEn: string,
  nameAr: string,
  elite: number,
  good: number,
  avg: number,
  unit: string,
  protocolEn: string,
  protocolAr: string,
  featured = false,
  modules: AnalyticsModuleId[] = MOD
) {
  return {
    key,
    categoryId: 'endurance' as const,
    icon: 'heart' as const,
    unit,
    referenceValues: refs(elite, good, avg),
    affectedModules: modules,
    analyticsWeight: 0.82,
    expectedTrend: 'up' as const,
    objective: 'aerobic_capacity' as const,
    featured,
    copy: copyBundle({
      name: { en: nameEn, ar: nameAr },
      description: {
        en: `Aerobic endurance field test: ${nameEn}.`,
        ar: `اختبار تحمل هوائي ميداني: ${nameAr}.`,
      },
      purpose: {
        en: 'Quantify aerobic capacity and repeat-effort endurance for team-sport profiling.',
        ar: 'قياس القدرة الهوائية وتحمل الجهد المتكرر لملف الرياضة الجماعية.',
      },
      equipment: { en: 'Track or marked course, stopwatch, cones', ar: 'مضمار أو مسار محدد، ساعة، أقماع' },
      protocol: { en: protocolEn, ar: protocolAr },
      scoring: { en: `Total distance or level achieved (${unit}). Higher is better.`, ar: `المسافة أو المستوى المحقق (${unit}). الأعلى أفضل.` },
      interpretation: {
        en: 'Compare against position-specific norms; track seasonal progression.',
        ar: 'قارن مع معايير المركز؛ تتبع التقدم الموسمي.',
      },
      aiRec: {
        en: 'Adjust conditioning volume if results drop >5% from baseline mid-season.',
        ar: 'عدّل حجم التهيئة إذا انخفضت النتائج >5% عن خط الأساس منتصف الموسم.',
      },
      notes: { en: 'Standardize environmental conditions and pacing strategy.', ar: 'وحّد الظروف البيئية واستراتيجية الإيقاع.' },
    }),
  };
}

export const ENDURANCE_TESTS: TestDefinition[] = defineTests([
  distance('cooper', 'Cooper 12-Minute Run', 'Cooper 12 دقيقة', 2800, 2400, 2000, 'm', 'Run maximal distance in 12 min on track; record meters.', 'اركض أقصى مسافة في 12 دقيقة؛ سجل الأمتار.', true),
  distance('yoyo', 'Yo-Yo Intermittent Recovery Level 1', 'Yo-Yo IR1', 1800, 1500, 1200, 'm', 'Standard Yo-Yo IR1 audio protocol; record total distance.', 'بروتوكول Yo-Yo IR1 صوتي؛ سجل المسافة الكلية.', false),
  distance('yoyo_ir2', 'Yo-Yo Intermittent Recovery Level 2', 'Yo-Yo IR2', 1200, 900, 600, 'm', 'Yo-Yo IR2 protocol for elite intermittent athletes.', 'بروتوكول Yo-Yo IR2 للرياضيين المتقطعين النخبة.', false, MOD_LOAD),
  {
    key: 'beep',
    categoryId: 'endurance',
    icon: 'heart',
    unit: 'level',
    referenceValues: refs(14, 11, 9),
    affectedModules: MOD,
    analyticsWeight: 0.78,
    expectedTrend: 'up',
    objective: 'aerobic_capacity',
    featured: false,
    copy: copyBundle({
      name: { en: 'Multi-Stage Fitness Test (Beep)', ar: 'اختبار Beep متعدد المراحل' },
      description: { en: 'Progressive shuttle run to exhaustion using standardized audio cues.', ar: 'جري shuttle تدريجي حتى الإرهاق بإشارات صوتية موحدة.' },
      purpose: { en: 'Estimate VO₂max and aerobic endurance via shuttle protocol.', ar: 'تقدير VO₂max والتحمل الهوائي عبر بروتوكول shuttle.' },
      equipment: { en: '20 m course, cones, beep test audio', ar: 'مسار 20م، أقماع، صوت beep test' },
      protocol: { en: 'Run 20 m shuttles synchronized to beeps; record final level and shuttles.', ar: 'shuttles 20م متزامنة مع الصوت؛ سجل المستوى والshuttles الأخيرة.' },
      scoring: { en: 'Final level achieved. Higher is better.', ar: 'المستوى النهائي. الأعلى أفضل.' },
      interpretation: { en: 'Level 12+ typical for elite field athletes.', ar: 'مستوى 12+ نموذجي للرياضيين الميدانيين النخبة.' },
      aiRec: { en: 'Supplement with interval training if level plateaus below target.', ar: 'أضف تدريب interval إذا ثبت المستوى دون الهدف.' },
    }),
  },
  {
    key: 'bruce',
    categoryId: 'endurance',
    icon: 'heart',
    unit: 'min',
    referenceValues: refs(12, 9, 6),
    affectedModules: MOD,
    analyticsWeight: 0.75,
    expectedTrend: 'up',
    objective: 'aerobic_capacity',
    featured: false,
    copy: copyBundle({
      name: { en: 'Bruce Treadmill Protocol', ar: 'بروتوكول Bruce treadmill' },
      description: { en: 'Graded treadmill test with increasing speed and grade until exhaustion.', ar: 'اختبار treadmill متدرج بزيادة السرعة والميل حتى الإرهاق.' },
      purpose: { en: 'Clinical-grade aerobic assessment; estimate VO₂max from stage duration.', ar: 'تقييم هوائي سريري؛ تقدير VO₂max من مدة المرحلة.' },
      equipment: { en: 'Motorized treadmill, HR monitor', ar: 'Treadmill آلي، مراقب HR' },
      protocol: { en: 'Standard Bruce stages; record total time and peak HR.', ar: 'مراحل Bruce قياسية؛ سجل الوقت الكلي وذروة HR.' },
      scoring: { en: 'Total test duration (min). Higher is better.', ar: 'مدة الاختبار الكلية (دق). الأعلى أفضل.' },
      interpretation: { en: 'Requires medical clearance; best for lab settings.', ar: 'يتطلب تصريحاً طبياً؛ الأفضل في المختبر.' },
      aiRec: { en: 'Use estimated VO₂max to set MAS and interval intensities.', ar: 'استخدم VO₂max المقدر لتحديد MAS وشدة interval.' },
      notes: { en: 'Not recommended within 48 h of heavy lower-body training.', ar: 'غير موصى به خلال 48 س من تدريب سفلي ثقيل.' },
    }),
  },
  {
    key: 'astrand',
    categoryId: 'endurance',
    icon: 'heart',
    unit: 'ml/kg/min',
    referenceValues: refs(55, 45, 35),
    affectedModules: MOD_LOAD,
    analyticsWeight: 0.85,
    expectedTrend: 'up',
    objective: 'aerobic_capacity',
    featured: false,
    copy: copyBundle({
      name: { en: 'Åstrand-Ryhming Cycle Test', ar: 'اختبار Åstrand-Ryhming' },
      description: { en: 'Submaximal cycle ergometer test extrapolating to VO₂max.', ar: 'اختبار ergometer دون أقصى مع استقراء VO₂max.' },
      purpose: { en: 'Estimate aerobic capacity without maximal exertion.', ar: 'تقدير القدرة الهوائية دون جهد أقصى.' },
      equipment: { en: 'Cycle ergometer, HR monitor, stopwatch', ar: 'Cycle ergometer، HR monitor، ساعة' },
      protocol: { en: '6 min steady-state at 100–150 W; HR 120–170 bpm; extrapolate VO₂max.', ar: '6 دق steady-state 100–150W؛ HR 120–170؛ استقراء VO₂max.' },
      scoring: { en: 'Estimated VO₂max (ml/kg/min). Higher is better.', ar: 'VO₂max المقدر (ml/kg/min). الأعلى أفضل.' },
      interpretation: { en: 'Valid when HR stabilizes within target range.', ar: 'صالح عند استقرار HR ضمن النطاق المستهدف.' },
      aiRec: { en: 'Retest every 6–8 weeks to track aerobic adaptations.', ar: 'أعد الاختبار كل 6–8 أسابيع لتتبع التكيف الهوائي.' },
    }),
  },
  {
    key: 'balke',
    categoryId: 'endurance',
    icon: 'heart',
    unit: 'min',
    referenceValues: refs(14, 12, 10),
    affectedModules: MOD,
    analyticsWeight: 0.7,
    expectedTrend: 'up',
    objective: 'aerobic_capacity',
    featured: false,
    copy: copyBundle({
      name: { en: 'Balke Treadmill Test', ar: 'اختبار Balke treadmill' },
      description: { en: 'Constant-speed treadmill test with 1% grade increase each minute.', ar: 'اختبار treadmill سرعة ثابتة مع زيادة 1% ميل كل دقيقة.' },
      purpose: { en: 'Simple graded test for VO₂max estimation in clinical settings.', ar: 'اختبار متدرج بسيط لتقدير VO₂max في الإعدادات السريرية.' },
      equipment: { en: 'Treadmill, HR monitor', ar: 'Treadmill، HR monitor' },
      protocol: { en: '3.3 mph constant; +1% grade/min until volitional fatigue.', ar: '3.3 mph ثابت؛ +1% ميل/دق حتى إرهاق اختياري.' },
      scoring: { en: 'Total time (min). Higher is better.', ar: 'الوقت الكلي (دق). الأعلى أفضل.' },
      interpretation: { en: 'VO₂max estimated from time using standard regression.', ar: 'VO₂max يُقدّر من الوقت بانحدار قياسي.' },
      aiRec: { en: 'Cross-validate with field tests for team-sport athletes.', ar: 'تحقق متقاطع مع اختبارات ميدانية للرياضيين الجماعيين.' },
    }),
  },
  {
    key: 'vo2max_est',
    categoryId: 'endurance',
    icon: 'heart',
    unit: 'ml/kg/min',
    referenceValues: refs(60, 50, 40),
    affectedModules: MOD_LOAD,
    analyticsWeight: 0.9,
    expectedTrend: 'up',
    objective: 'aerobic_capacity',
    featured: false,
    copy: copyBundle({
      name: { en: 'VO₂max Estimate (Field)', ar: 'تقدير VO₂max (ميداني)' },
      description: { en: 'Field-derived VO₂max from Cooper, beep, or shuttle regression equations.', ar: 'VO₂max ميداني من معادلات Cooper أو beep أو shuttle.' },
      purpose: { en: 'Unified aerobic capacity metric for analytics and load planning.', ar: 'مقياس هوائي موحد للتحليلات وتخطيط الحمل.' },
      equipment: { en: 'Depends on source test (track, audio, HR monitor)', ar: 'حسب الاختبار المصدر (مضمار، صوت، HR)' },
      protocol: { en: 'Perform source test; apply validated regression to estimate VO₂max.', ar: 'نفّذ الاختبار المصدر؛ طبّق انحداراً معتمداً لتقدير VO₂max.' },
      scoring: { en: 'Estimated VO₂max (ml/kg/min). Higher is better.', ar: 'VO₂max المقدر. الأعلى أفضل.' },
      interpretation: { en: 'Elite team-sport athletes typically 50–65 ml/kg/min.', ar: 'النخبة الجماعية عادة 50–65 ml/kg/min.' },
      aiRec: { en: 'Set aerobic training zones from estimated VO₂max and MAS.', ar: 'حدد مناطق التدريب الهوائي من VO₂max وMAS المقدرين.' },
    }),
  },
  {
    key: 'mas',
    categoryId: 'endurance',
    icon: 'speedometer',
    unit: 'km/h',
    referenceValues: refs(18, 15, 12),
    affectedModules: MOD_LOAD,
    analyticsWeight: 0.83,
    expectedTrend: 'up',
    objective: 'aerobic_capacity',
    featured: false,
    copy: copyBundle({
      name: { en: 'Maximal Aerobic Speed (MAS)', ar: 'السرعة الهوائية القصوى MAS' },
      description: { en: 'Running speed at VO₂max from field test or incremental treadmill.', ar: 'سرعة الجري عند VO₂max من اختبار ميداني أو treadmill متدرج.' },
      purpose: { en: 'Anchor interval prescription (% MAS) for conditioning programs.', ar: 'مرساة وصف interval (% MAS) لبرامج التهيئة.' },
      equipment: { en: 'Track, timing gates, or treadmill with speed control', ar: 'مضمار، بوابات توقيت، أو treadmill' },
      protocol: { en: '30–15 IFT or Vameval protocol; record last completed speed.', ar: 'بروتوكول 30–15 IFT أو Vameval؛ سجل آخر سرعة مكتملة.' },
      scoring: { en: 'MAS (km/h). Higher is better.', ar: 'MAS (km/h). الأعلى أفضل.' },
      interpretation: { en: 'Typical interval intensities: 100–120% MAS for HIIT.', ar: 'شدة interval نموذجية: 100–120% MAS لـ HIIT.' },
      aiRec: { en: 'Recalculate MAS after each aerobic retest block.', ar: 'أعد حساب MAS بعد كل كتلة retest هوائي.' },
    }),
  },
  {
    key: 'lactate_threshold',
    categoryId: 'endurance',
    icon: 'water',
    unit: '% HRmax',
    referenceValues: refs(85, 75, 65),
    affectedModules: ['endurance', 'training_load', 'fatigue'],
    analyticsWeight: 0.87,
    expectedTrend: 'up',
    objective: 'aerobic_capacity',
    featured: false,
    copy: copyBundle({
      name: { en: 'Lactate Threshold (LT)', ar: 'عتبة Lactate LT' },
      description: { en: 'Intensity at lactate turnpoint via incremental test and blood sampling.', ar: 'الشدة عند نقطة تحول lactate عبر اختبار متدرج وعينات دم.' },
      purpose: { en: 'Define aerobic–anaerobic transition for precise endurance zone training.', ar: 'تحديد انتقال هوائي–لاهوائي لتدريب تحمل دقيق.' },
      equipment: { en: 'Treadmill or bike, lactate analyzer, HR monitor', ar: 'Treadmill أو دراجة، محلل lactate، HR monitor' },
      protocol: { en: '3–5 min stages; blood lactate each stage; identify LT1/LT2.', ar: 'مراحل 3–5 دق؛ lactate دم كل مرحلة؛ حدد LT1/LT2.' },
      scoring: { en: 'LT as % HRmax or speed (km/h). Higher is better.', ar: 'LT كنسبة % HRmax أو سرعة. الأعلى أفضل.' },
      interpretation: { en: 'LT improvement indicates enhanced aerobic efficiency.', ar: 'تحسن LT يدل على كفاءة هوائية أعلى.' },
      aiRec: { en: 'Program tempo runs at 90–95% LT pace during base phases.', ar: 'برمجج tempo runs عند 90–95% إيقاع LT في مراحل القاعدة.' },
      notes: { en: 'Requires finger-prick or earlobe sampling; lab setting preferred.', ar: 'يتطلب عينة إصبع أو شحمة أذن؛ يُفضل المختبر.' },
    }),
  },
]);
