import type { AnalyticsModuleId } from '@/src/analytics/types';
import { copyBundle, defineTests, refs } from '../factory';
import type { TestDefinition } from '../../types';

const MOD: AnalyticsModuleId[] = ['strength', 'physical_fitness', 'training_load'];
const MOD_LOAD: AnalyticsModuleId[] = ['strength', 'training_load'];

function rm(
  key: string,
  nameEn: string,
  nameAr: string,
  elite: number,
  good: number,
  avg: number,
  protocolEn: string,
  protocolAr: string,
  featured = false
) {
  return {
    key,
    categoryId: 'strength' as const,
    icon: 'barbell' as const,
    unit: 'kg',
    referenceValues: refs(elite, good, avg),
    affectedModules: MOD,
    analyticsWeight: 0.85,
    expectedTrend: 'up' as const,
    objective: 'max_force' as const,
    featured,
    copy: copyBundle({
      name: { en: nameEn, ar: nameAr },
      description: {
        en: `One-repetition maximum (${nameEn}) strength assessment.`,
        ar: `تقييم قوة ${nameAr} بحد أقصى لتكرار واحد.`,
      },
      purpose: {
        en: 'Establish maximal force capacity for load prescription and strength profiling.',
        ar: 'تحديد القدرة القصوى على القوة لوصف الأحمال وملف القوة.',
      },
      equipment: { en: 'Barbell, rack, safety pins, spotter', ar: 'بارbell، حامل، دبابيس أمان، مساعد' },
      protocol: { en: protocolEn, ar: protocolAr },
      scoring: { en: 'Highest successful 1RM (kg). Higher is better.', ar: 'أعلى 1RM ناجح (كغ). الأعلى أفضل.' },
      interpretation: {
        en: 'Compare relative to body mass and position norms; track across mesocycles.',
        ar: 'قارن نسبة إلى كتلة الجسم ومعايير المركز؛ تتبع عبر الدورات.',
      },
      aiRec: {
        en: 'Adjust training load if 1RM plateaus >3 weeks; deload when velocity loss exceeds 20%.',
        ar: 'عدّل الحمل إذا ثبت 1RM >3 أسابيع؛ خفّف عند فقدان سرعة >20%.',
      },
      notes: { en: 'Standardize depth, grip, and rest intervals between attempts.', ar: 'وحّد العمق والقبضة والراحة بين المحاولات.' },
    }),
  };
}

export const STRENGTH_TESTS: TestDefinition[] = defineTests([
  rm('squat_1rm', 'Back Squat 1RM', 'Squat 1RM', 180, 150, 120, 'Warm-up sets; incremental loading to true 1RM with 3–5 min rest.', 'إحماء؛ زيادة تدريجية إلى 1RM حقيقي مع راحة 3–5 دق.', true),
  rm('bench_1rm', 'Bench Press 1RM', 'Bench 1RM', 140, 115, 90, 'Competition-style pause bench; spotter required; best of three attempts.', 'Bench بإيقاف؛ مساعد مطلوب؛ أفضل 3 محاولات.', false),
  rm('deadlift_1rm', 'Deadlift 1RM', 'Deadlift 1RM', 220, 180, 150, 'Conventional or sumo; belt optional; record highest legal lockout.', 'تقليدي أو sumo؛ حزام اختياري؛ سجل أعلى lockout قانوني.', false),
  {
    key: 'grip_strength',
    categoryId: 'strength',
    icon: 'hand-left',
    unit: 'kg',
    referenceValues: refs(60, 50, 40),
    affectedModules: MOD,
    analyticsWeight: 0.7,
    expectedTrend: 'up',
    objective: 'max_force',
    featured: false,
    copy: copyBundle({
      name: { en: 'Grip Strength (Dynamometer)', ar: 'قوة القبضة (Dynamometer)' },
      description: { en: 'Isometric hand grip force measured with a calibrated dynamometer.', ar: 'قوة قبضة يد isometric بمقياس معاير.' },
      purpose: { en: 'Screen upper-limb force and neuromuscular readiness; correlate with contact sports.', ar: 'فحص قوة الطرف العلوي والجاهزية؛ يرتبط برياضات التصادم.' },
      equipment: { en: 'Hand dynamometer, chair, standardized arm position', ar: 'مقياس قبضة، كرسي، وضعية ذراع موحدة' },
      protocol: { en: 'Seated; elbow 90°; three trials each hand; record best per side and mean.', ar: 'جلوس؛ مرفق 90°؛ 3 محاولات لكل يد؛ سجل الأفضل والمتوسط.' },
      scoring: { en: 'Peak force (kg). Higher is better.', ar: 'ذروة القوة (كغ). الأعلى أفضل.' },
      interpretation: { en: 'Asymmetry >10% may indicate injury risk or fatigue.', ar: 'عدم تناظر >10% قد يدل على خطر إصابة أو إرهاق.' },
      aiRec: { en: 'Add grip-specific work if below position norms; monitor asymmetry trends.', ar: 'أضف عمل قبضة إذا دون المعايير؛ راقب اتجاه عدم التناظر.' },
      notes: { en: 'Avoid testing immediately post heavy upper-body session.', ar: 'تجنب الاختبار مباشرة بعد جلسة علوية ثقيلة.' },
    }),
  },
  {
    key: 'imtp',
    categoryId: 'strength',
    icon: 'analytics',
    unit: 'N',
    referenceValues: refs(3500, 2800, 2200),
    affectedModules: MOD_LOAD,
    analyticsWeight: 0.88,
    expectedTrend: 'up',
    objective: 'max_force',
    featured: false,
    copy: copyBundle({
      name: { en: 'Isometric Mid-Thigh Pull (IMTP)', ar: 'سحب isometric منتصف الفخذ IMTP' },
      description: { en: 'Peak isometric force from fixed mid-thigh position on force plate.', ar: 'ذروة قوة isometric من وضع ثابت منتصف الفخذ على force plate.' },
      purpose: { en: 'Assess maximal force without eccentric fatigue; useful for monitoring neuromuscular status.', ar: 'تقييم القوة القصوى دون إرهاق eccentric؛ مفيد لمراقبة الحالة العصبية العضلية.' },
      equipment: { en: 'Force plate, IMTP bar, chain or straps', ar: 'Force plate، بار IMTP، سلسلة أو أحزمة' },
      protocol: { en: 'Knee ~125°; pull maximally for 3–5 s; three trials with 2 min rest.', ar: 'ركبة ~125°؛ اسحب بأقصى قوة 3–5 ث؛ 3 محاولات راحة 2 دق.' },
      scoring: { en: 'Peak force (N) and relative force (N/kg).', ar: 'ذروة القوة (N) والقوة النسبية (N/كغ).' },
      interpretation: { en: 'Drop >5% from baseline may signal fatigue or under-recovery.', ar: 'انخفاض >5% عن خط الأساس قد يشير لإرهاق أو نقص تعافٍ.' },
      aiRec: { en: 'Use IMTP trends to modulate weekly training load and taper timing.', ar: 'استخدم اتجاهات IMTP لتعديل الحمل الأسبوعي وتوقيت التaper.' },
    }),
  },
  {
    key: 'nordic_hamstring',
    categoryId: 'strength',
    icon: 'fitness',
    unit: 'N',
    referenceValues: refs(450, 350, 250),
    affectedModules: ['strength', 'injury_risk', 'physical_fitness'],
    analyticsWeight: 0.8,
    expectedTrend: 'up',
    objective: 'max_force',
    featured: false,
    copy: copyBundle({
      name: { en: 'Nordic Hamstring Eccentric', ar: 'Nordic Hamstring eccentric' },
      description: { en: 'Eccentric hamstring strength via Nordic curl with force or angle measurement.', ar: 'قوة hamstring eccentric عبر Nordic curl مع قياس قوة أو زاوية.' },
      purpose: { en: 'Reduce hamstring injury risk; assess eccentric capacity for sprint sports.', ar: 'تقليل خطر إصابة hamstring؛ تقييم القدرة eccentric لرياضات السرعة.' },
      equipment: { en: 'Anchor pad, partner or strap, optional force cell', ar: 'وسادة تثبيت، شريك أو حزام، force cell اختياري' },
      protocol: { en: 'Kneeling Nordic; partner holds ankles; maximal controlled lowering; three trials.', ar: 'Nordic ركوع؛ شريك يثبت الكاحلين؛ خفض controlled أقصى؛ 3 محاولات.' },
      scoring: { en: 'Peak eccentric force (N) or break angle (°). Higher force / smaller angle is better.', ar: 'ذروة قوة eccentric (N) أو زاوية كسر (°). قوة أعلى / زاوية أصغر أفضل.' },
      interpretation: { en: 'Low eccentric capacity correlates with hamstring strain incidence.', ar: 'قدرة eccentric منخفقة ترتبط بإصابات hamstring.' },
      aiRec: { en: 'Prescribe Nordic progressions if below norms; maintain in-season.', ar: 'صف تقدم Nordic إذا دون المعايير؛ حافظ في الموسم.' },
      notes: { en: 'Ensure adequate warm-up; stop if cramping occurs.', ar: 'تأكد من إحماء كافٍ؛ توقف عند تشنج.' },
    }),
  },
  {
    key: 'pullup',
    categoryId: 'strength',
    icon: 'arrow-up',
    unit: 'reps',
    referenceValues: refs(20, 12, 6),
    affectedModules: MOD,
    analyticsWeight: 0.75,
    expectedTrend: 'up',
    objective: 'max_force',
    featured: false,
    copy: copyBundle({
      name: { en: 'Pull-Up Max Reps', ar: 'Pull-Up أقصى تكرارات' },
      description: { en: 'Maximum consecutive strict pull-ups to chin-over-bar.', ar: 'أقصى pull-ups متتالية strict مع ذقن فوق البار.' },
      purpose: { en: 'Assess relative upper-body pulling strength and muscular endurance.', ar: 'تقييم قوة السحب العلوية النسبية وتحمل العضلات.' },
      equipment: { en: 'Pull-up bar, chalk optional', ar: 'بار pull-up، طباشير اختياري' },
      protocol: { en: 'Overhand grip; full hang to chin over bar; no kipping; one attempt.', ar: 'قبضة overhand؛ تعليق كامل إلى ذقن فوق البار؛ بدون kipping؛ محاولة واحدة.' },
      scoring: { en: 'Total strict repetitions. Higher is better.', ar: 'إجمالي التكرارات strict. الأعلى أفضل.' },
      interpretation: { en: 'Normalize by body mass for cross-athlete comparison.', ar: 'طبّع بكتلة الجسم للمقارنة بين الرياضيين.' },
      aiRec: { en: 'Add eccentric and isometric progressions if reps plateau.', ar: 'أضف تقدم eccentric و isometric إذا ثبتت التكرارات.' },
    }),
  },
  {
    key: 'pushup',
    categoryId: 'strength',
    icon: 'body',
    unit: 'reps',
    referenceValues: refs(50, 35, 20),
    affectedModules: ['strength', 'physical_fitness'],
    analyticsWeight: 0.65,
    expectedTrend: 'up',
    objective: 'max_force',
    featured: false,
    copy: copyBundle({
      name: { en: 'Push-Up Max Reps', ar: 'Push-Up أقصى تكرارات' },
      description: { en: 'Maximum consecutive strict push-ups in one set.', ar: 'أقصى push-ups متتالية strict في مجموعة واحدة.' },
      purpose: { en: 'Screen upper-body pushing endurance and core stability under fatigue.', ar: 'فحص تحمل الدفع العلوي واستقرار الجذع تحت الإرهاق.' },
      equipment: { en: 'Flat floor, metronome optional (60 bpm)', ar: 'أرضية مستوية، metronome اختياري (60 bpm)' },
      protocol: { en: 'Hands shoulder-width; chest to floor; full extension; continuous tempo.', ar: 'يدان عرض الكتف؛ صدر للأرض؛ extension كامل؛ إيقاع مستمر.' },
      scoring: { en: 'Total valid repetitions. Higher is better.', ar: 'إجمالي التكرارات الصحيحة. الأعلى أفضل.' },
      interpretation: { en: 'Useful field test when gym access is limited.', ar: 'اختبار ميداني مفيد عند محدودية الوصول للصالة.' },
      aiRec: { en: 'Pair with bench press data for comprehensive pushing profile.', ar: 'اقترن مع bench press لملف دفع شامل.' },
    }),
  },
  {
    key: 'med_ball_throw',
    categoryId: 'strength',
    icon: 'baseball',
    unit: 'm',
    referenceValues: refs(12, 10, 8),
    affectedModules: ['strength', 'physical_fitness'],
    analyticsWeight: 0.72,
    expectedTrend: 'up',
    objective: 'max_force',
    featured: false,
    copy: copyBundle({
      name: { en: 'Medicine Ball Chest Throw', ar: 'رمي كرة طبية صدر' },
      description: { en: 'Seated or standing explosive chest pass for maximal distance.', ar: 'تمرير صدر explosive جلوس أو وقوف لأقصى مسافة.' },
      purpose: { en: 'Assess upper-body power output in a sport-specific pushing pattern.', ar: 'تقييم قدرة الدفع العلوية explosive في نمط رياضي.' },
      equipment: { en: '3–5 kg medicine ball, tape measure', ar: 'كرة طبية 3–5 كغ، شريط قياس' },
      protocol: { en: 'Seated against wall or standing; three maximal throws; record best distance.', ar: 'جلوس مقابل جدار أو وقوف؛ 3 رميات أقصى؛ سجل أفضل مسافة.' },
      scoring: { en: 'Best throw distance (m). Higher is better.', ar: 'أفضل مسافة رمية (م). الأعلى أفضل.' },
      interpretation: { en: 'Sensitive to technique; standardize ball mass and release angle.', ar: 'حساس للتقنية؛ وحّد كتلة الكرة وزاوية الإطلاق.' },
      aiRec: { en: 'Integrate with CMJ for upper–lower power ratio analysis.', ar: 'ادمج مع CMJ لتحليل نسبة القوة العلوية–السفلية.' },
    }),
  },
  rm('leg_press', 'Leg Press 1RM', 'Leg Press 1RM', 300, 250, 200, '45° sled leg press; feet shoulder-width; full ROM to safety stop.', 'Leg press 45°؛ قدمان عرض الكتف؛ ROM كامل حتى stop.', false),
]);
