export * from './types';
export { WEARABLE_PROVIDERS, getProviderById, getPremiumProviders, PREMIUM_PROVIDER_IDS } from './registry/providerRegistry';
export type { WearableProviderAdapter } from './adapters/baseAdapter';
export { getWearableAdapter, isPlaceholderProvider } from './adapters/placeholderAdapters';
export { createMockAdapter, generateMockSyncRecord } from './adapters/mockAdapter';
export { buildWearableDailySnapshot, mergeWearableRecord, hasWearableData } from './engine/wearablesEngine';
export { buildWearableSignals } from './utils/wearableSignals';
export { formatWearablesForAI, buildWearableReportSummary } from './utils/wearableHelpers';
export { getMockDeviceMeta } from './utils/mockDeviceMeta';
export { buildSyncHistoryTimeline } from './utils/syncHistoryBuilder';
export { useWearablesSnapshot, useWearablesDashboardSummary } from './hooks/useWearablesSnapshot';
export { ProviderCard } from './components/ProviderCard';
export { ConnectDevicesPanel } from './components/ConnectDevicesPanel';
export { PremiumProviderCard } from './components/PremiumProviderCard';
export { LiveMetricsGrid } from './components/LiveMetricsGrid';
export { SyncHistoryTimeline } from './components/SyncHistoryTimeline';
export { DeviceHealthCard } from './components/DeviceHealthCard';
export { WearablesDeviceCenter } from './components/WearablesDeviceCenter';
export { WorkspaceWearablesSection } from './components/WorkspaceWearablesSection';
