export {
  isEvidenceTier,
  isScientificCategoryCode,
  isDataSourceType,
  isAssessmentKey,
  validateBilingualText,
  validateVersionMeta,
  validateCatalogAssessmentDefinition,
  validateAssessmentProtocolVersion,
  validateCatalogNormativeReference,
  validateNormativeBands,
  isNormativeSourceQuality,
  validateScientificOrganization,
  validateOrgAthlete,
  validateOrgEquipment,
  mergeValidation,
} from './scientificValidators';
